name: main
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - run: |
          ./mvnw -Dbigquery.project.arg="-Dbigquery.project=dummy-project" \
            clean \
            spotless:check \
            checkstyle:checkstyle \
            findbugs:findbugs \
            test
